# coding: utf-8

"""
    coinMerchant Api Documentation

    To generate an API key, please visit <a href='https://pay.coinsecure.in/payment-tools/api' target='_new' class='homeapi'>https://pay.coinsecure.in/payment-tools/api</a>.<br>Guidelines for use can be accessed at <a href='https://pay.coinsecure.in/api/guidelines'>https://pay.coinsecure.in/api/guidelines</a>.

    OpenAPI spec version: 1.0B
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.invoice_actions_api import InvoiceActionsApi


class TestInvoiceActionsApi(unittest.TestCase):
    """ InvoiceActionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.invoice_actions_api.InvoiceActionsApi()

    def tearDown(self):
        pass

    def test_create_new_invoice(self):
        """
        Test case for create_new_invoice

        NEW INVOICE
        """
        pass

    def test_load_invoice(self):
        """
        Test case for load_invoice

        
        """
        pass


if __name__ == '__main__':
    unittest.main()