/**
 * Coinsecure Api Documentation
 * To generate an API key, please visit <a href='https://coinsecure.in/api' target='_new' class='homeapi'>https://coinsecure.in/api</a>.<br>Guidelines for use can be accessed at <a href='https://api.coinsecure.in/v1/guidelines'>https://api.coinsecure.in/v1/guidelines</a>.<br>Programming Language Libraries for use can be accessed at <a href='https://api.coinsecure.in/v1/code-libraries'>https://api.coinsecure.in/v1/code-libraries</a>.
 *
 * OpenAPI spec version: beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGConfirmData.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGConfirmData::SWGConfirmData(QString* json) {
    init();
    this->fromJson(*json);
}

SWGConfirmData::SWGConfirmData() {
    init();
}

SWGConfirmData::~SWGConfirmData() {
    this->cleanup();
}

void
SWGConfirmData::init() {
    confirmations = 0L;
}

void
SWGConfirmData::cleanup() {
    
}

SWGConfirmData*
SWGConfirmData::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGConfirmData::fromJsonObject(QJsonObject &pJson) {
    setValue(&confirmations, pJson["confirmations"], "qint64", "");
}

QString
SWGConfirmData::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGConfirmData::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("confirmations", QJsonValue(confirmations));

    return obj;
}

qint64
SWGConfirmData::getConfirmations() {
    return confirmations;
}
void
SWGConfirmData::setConfirmations(qint64 confirmations) {
    this->confirmations = confirmations;
}



} /* namespace Swagger */

