/**
 * Coinsecure Api Documentation
 * To generate an API key, please visit <a href='https://coinsecure.in/api' target='_new' class='homeapi'>https://coinsecure.in/api</a>.<br>Guidelines for use can be accessed at <a href='https://api.coinsecure.in/v1/guidelines'>https://api.coinsecure.in/v1/guidelines</a>.<br>Programming Language Libraries for use can be accessed at <a href='https://api.coinsecure.in/v1/code-libraries'>https://api.coinsecure.in/v1/code-libraries</a>.
 *
 * OpenAPI spec version: beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGLastTradeData.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGLastTradeData::SWGLastTradeData(QString* json) {
    init();
    this->fromJson(*json);
}

SWGLastTradeData::SWGLastTradeData() {
    init();
}

SWGLastTradeData::~SWGLastTradeData() {
    this->cleanup();
}

void
SWGLastTradeData::init() {
    time = 0L;
    avg_rate = 0L;
    vol = 0L;
    ord_type = new QString("");
}

void
SWGLastTradeData::cleanup() {
    



    if(ord_type != nullptr) {
        delete ord_type;
    }
}

SWGLastTradeData*
SWGLastTradeData::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGLastTradeData::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&time, pJson["time"], "qint64", "");
    ::Swagger::setValue(&avg_rate, pJson["avg_rate"], "qint64", "");
    ::Swagger::setValue(&vol, pJson["vol"], "qint64", "");
    ::Swagger::setValue(&ord_type, pJson["ord_type"], "QString", "QString");
}

QString
SWGLastTradeData::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGLastTradeData::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("time", QJsonValue(time));

    obj->insert("avg_rate", QJsonValue(avg_rate));

    obj->insert("vol", QJsonValue(vol));

    toJsonValue(QString("ord_type"), ord_type, obj, QString("QString"));

    return obj;
}

qint64
SWGLastTradeData::getTime() {
    return time;
}
void
SWGLastTradeData::setTime(qint64 time) {
    this->time = time;
}

qint64
SWGLastTradeData::getAvgRate() {
    return avg_rate;
}
void
SWGLastTradeData::setAvgRate(qint64 avg_rate) {
    this->avg_rate = avg_rate;
}

qint64
SWGLastTradeData::getVol() {
    return vol;
}
void
SWGLastTradeData::setVol(qint64 vol) {
    this->vol = vol;
}

QString*
SWGLastTradeData::getOrdType() {
    return ord_type;
}
void
SWGLastTradeData::setOrdType(QString* ord_type) {
    this->ord_type = ord_type;
}



} /* namespace Swagger */

