//
// CodeCountryMobile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CodeCountryMobile: JSONEncodable {
    public var code: String?
    public var countryCode: String?
    public var phoneNumber: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["code"] = self.code
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["phoneNumber"] = self.phoneNumber
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
