//
// NewFiatBankDeposit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NewFiatBankDeposit: JSONEncodable {
    public var amount: Int64?
    public var message: String?
    public var bank: String?
    public var depType: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["amount"] = self.amount?.encodeToJSON()
        nillableDictionary["message"] = self.message
        nillableDictionary["bank"] = self.bank
        nillableDictionary["depType"] = self.depType
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
