//
// WalletCoinWithdrawData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class WalletCoinWithdrawData: JSONEncodable {
    public var timeDetails: TimeData?
    public var txID: String?
    public var message: String?
    public var satoshis: Int64?
    public var walletID: String?
    public var withdrawID: String?
    public var sentTo: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["timeDetails"] = self.timeDetails?.encodeToJSON()
        nillableDictionary["txID"] = self.txID
        nillableDictionary["message"] = self.message
        nillableDictionary["satoshis"] = self.satoshis?.encodeToJSON()
        nillableDictionary["walletID"] = self.walletID
        nillableDictionary["withdrawID"] = self.withdrawID
        nillableDictionary["sentTo"] = self.sentTo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
