//
// Merchant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Merchant: JSONEncodable {
    public var firstName: String?
    public var lastName: String?
    public var coinBalance: Int64?
    public var fiatBalance: Int64?
    public var merchantType: String?
    public var organization: String?
    public var status: String?
    public var website: String?
    public var address: String?
    public var adminEmail: String?
    public var businessType: String?
    public var info: String?
    public var minCoinSettlement: Int64?
    public var minFiatSettlement: Int64?
    public var tel: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["coinBalance"] = self.coinBalance?.encodeToJSON()
        nillableDictionary["fiatBalance"] = self.fiatBalance?.encodeToJSON()
        nillableDictionary["merchantType"] = self.merchantType
        nillableDictionary["organization"] = self.organization
        nillableDictionary["status"] = self.status
        nillableDictionary["website"] = self.website
        nillableDictionary["address"] = self.address
        nillableDictionary["adminEmail"] = self.adminEmail
        nillableDictionary["businessType"] = self.businessType
        nillableDictionary["info"] = self.info
        nillableDictionary["minCoinSettlement"] = self.minCoinSettlement?.encodeToJSON()
        nillableDictionary["minFiatSettlement"] = self.minFiatSettlement?.encodeToJSON()
        nillableDictionary["tel"] = self.tel
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
