/*
 * Coinsecure Api Documentation
 * To generate an API key, please visit <a href='https://coinsecure.in/api' target='_new' class='homeapi'>https://coinsecure.in/api</a>.<br>Guidelines for use can be accessed at <a href='https://api.coinsecure.in/v1/guidelines'>https://api.coinsecure.in/v1/guidelines</a>.<br>Programming Language Libraries for use can be accessed at <a href='https://api.coinsecure.in/v1/code-libraries'>https://api.coinsecure.in/v1/code-libraries</a>.
 *
 * OpenAPI spec version: beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TradeSummaryData
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-27T22:11:57.435Z")
public class TradeSummaryData {
  @SerializedName("completedAsksSum")
  private Long completedAsksSum = null;

  @SerializedName("completedBidsSum")
  private Long completedBidsSum = null;

  @SerializedName("completedAsksCount")
  private Long completedAsksCount = null;

  @SerializedName("completedBidsCount")
  private Long completedBidsCount = null;

  @SerializedName("pendingAsksCount")
  private Long pendingAsksCount = null;

  @SerializedName("pendingBidsCount")
  private Long pendingBidsCount = null;

  public TradeSummaryData completedAsksSum(Long completedAsksSum) {
    this.completedAsksSum = completedAsksSum;
    return this;
  }

   /**
   * Get completedAsksSum
   * @return completedAsksSum
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getCompletedAsksSum() {
    return completedAsksSum;
  }

  public void setCompletedAsksSum(Long completedAsksSum) {
    this.completedAsksSum = completedAsksSum;
  }

  public TradeSummaryData completedBidsSum(Long completedBidsSum) {
    this.completedBidsSum = completedBidsSum;
    return this;
  }

   /**
   * Get completedBidsSum
   * @return completedBidsSum
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getCompletedBidsSum() {
    return completedBidsSum;
  }

  public void setCompletedBidsSum(Long completedBidsSum) {
    this.completedBidsSum = completedBidsSum;
  }

  public TradeSummaryData completedAsksCount(Long completedAsksCount) {
    this.completedAsksCount = completedAsksCount;
    return this;
  }

   /**
   * Get completedAsksCount
   * @return completedAsksCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getCompletedAsksCount() {
    return completedAsksCount;
  }

  public void setCompletedAsksCount(Long completedAsksCount) {
    this.completedAsksCount = completedAsksCount;
  }

  public TradeSummaryData completedBidsCount(Long completedBidsCount) {
    this.completedBidsCount = completedBidsCount;
    return this;
  }

   /**
   * Get completedBidsCount
   * @return completedBidsCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getCompletedBidsCount() {
    return completedBidsCount;
  }

  public void setCompletedBidsCount(Long completedBidsCount) {
    this.completedBidsCount = completedBidsCount;
  }

  public TradeSummaryData pendingAsksCount(Long pendingAsksCount) {
    this.pendingAsksCount = pendingAsksCount;
    return this;
  }

   /**
   * Get pendingAsksCount
   * @return pendingAsksCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getPendingAsksCount() {
    return pendingAsksCount;
  }

  public void setPendingAsksCount(Long pendingAsksCount) {
    this.pendingAsksCount = pendingAsksCount;
  }

  public TradeSummaryData pendingBidsCount(Long pendingBidsCount) {
    this.pendingBidsCount = pendingBidsCount;
    return this;
  }

   /**
   * Get pendingBidsCount
   * @return pendingBidsCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getPendingBidsCount() {
    return pendingBidsCount;
  }

  public void setPendingBidsCount(Long pendingBidsCount) {
    this.pendingBidsCount = pendingBidsCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeSummaryData tradeSummaryData = (TradeSummaryData) o;
    return Objects.equals(this.completedAsksSum, tradeSummaryData.completedAsksSum) &&
        Objects.equals(this.completedBidsSum, tradeSummaryData.completedBidsSum) &&
        Objects.equals(this.completedAsksCount, tradeSummaryData.completedAsksCount) &&
        Objects.equals(this.completedBidsCount, tradeSummaryData.completedBidsCount) &&
        Objects.equals(this.pendingAsksCount, tradeSummaryData.pendingAsksCount) &&
        Objects.equals(this.pendingBidsCount, tradeSummaryData.pendingBidsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completedAsksSum, completedBidsSum, completedAsksCount, completedBidsCount, pendingAsksCount, pendingBidsCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeSummaryData {\n");
    
    sb.append("    completedAsksSum: ").append(toIndentedString(completedAsksSum)).append("\n");
    sb.append("    completedBidsSum: ").append(toIndentedString(completedBidsSum)).append("\n");
    sb.append("    completedAsksCount: ").append(toIndentedString(completedAsksCount)).append("\n");
    sb.append("    completedBidsCount: ").append(toIndentedString(completedBidsCount)).append("\n");
    sb.append("    pendingAsksCount: ").append(toIndentedString(pendingAsksCount)).append("\n");
    sb.append("    pendingBidsCount: ").append(toIndentedString(pendingBidsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

